/**
 * api.core
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityAreaResponseDTO } from './activityAreaResponseDTO';
import { FieldOfInterestTagResponseDTO } from './fieldOfInterestTagResponseDTO';

export interface UserResponseDTO { 
    id?: string;
    name?: string;
    email?: string;
    avatarUrl?: string;
    type?: string;
    organization?: string;
    activityArea?: ActivityAreaResponseDTO;
    fieldsOfInterests?: Array<FieldOfInterestTagResponseDTO>;
    isActive?: boolean;
    hasLoggedIn?: boolean;
    profileDescription?: string;
    facebookLink?: string;
    instagramLink?: string;
    tikTokLink?: string;
    xLink?: string;
    discordLink?: string;
    linkedInLink?: string;
    redditLink?: string;
    webSiteLink?: string;
    createdAt?: Date;
    updatedAt?: Date;
}