/**
 * api.core
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityAreaResponseDTO } from './activityAreaResponseDTO.interface';

/**
 * A common data response to return to the front end. Data or Error should be set but not  at the same time.
 */
export interface ActivityAreaResponseDTOResponse {
    data?: ActivityAreaResponseDTO;
    error?: ActivityAreaResponseDTO;
}
