/**
 * api.core
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ApiOrganizerdraftsBody { 
    title?: string;
    content?: string;
    publicationDate?: Date;
    eventStartDate?: Date;
    eventEndDate?: Date;
    imageAltText?: string;
    /**
     * Either this field should be set (not null) or the ImageUrl string field should be set  If none of them are set, the creation will fail
     */
    image?: Blob;
    /**
     * Either this field should be set (not null) or the Image FormFile field should be set  If none of them are set, the creation will fail
     */
    imageUrl?: string;
    tags?: Array<string>;
}