/**
 * api.core
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ModeratorCreateRequestDTO { 
    /**
     * This id when passed needs to be already created in supabase.
     */
    id?: string;
    /**
     * A email that will be bound to the moderator, make sure that this email match the   user in supabase of the given id.
     */
    email?: string;
}