/**
 * api.core
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserUpdateDTO { 
    id?: string;
    email?: string;
    organization?: string;
    activityAreaId?: string;
    hasLoggedIn?: boolean;
    profileDescription?: string;
    facebookLink?: string;
    instagramLink?: string;
    tikTokLink?: string;
    xLink?: string;
    discordLink?: string;
    linkedInLink?: string;
    redditLink?: string;
    webSiteLink?: string;
}